dist: trusty
sudo: required
language: generic
services: docker
compiler: 
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install:
    - sudo apt-get -qq update

script:
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CXX to tell cmake which compiler to use
  - export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - g++ -v && cmake --version
  - make -C test
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  - docker pull dxjoke/tectonic-docker
  # Compiling multiple files as well as using biber:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 tex/main.tex; biber tex/main; tectonic tex/main.tex"
  - bash <(curl -s https://codecov.io/bash) 
